### ISSUE TITLE
Compilation fails with Elixir 1.8 and OTP 21

### ISSUE THREAD

**Issue by soundmonster** [holsee/spirit_fingers#1]
SpiritFingers contains a NIF that has to be compiled after installation. I was trying  to compile it but it fails with this message:

```
$ mix deps.compile
...
==> spirit_fingers
Compiling NIF crate :simhash (native/simhash)...
   Compiling erlang_nif-sys v0.6.3
   Compiling syn v0.11.11
error: failed to run custom build command for `erlang_nif-sys v0.6.3`
process didn't exit successfully: `/Users/leonid/Projects/ex_lsh/_build/dev/rustler_crates/simhash/release/build/erlang_nif-sys-bf350dda8055f7a2/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /Users/leonid/.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.3/build.rs:28:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

After looking up on Rustler, I figured out that the NIF version I need is 2.14, so I tried this

```
RUSTLER_NIF_VERSION=2.14 mix deps.compile
```
but it fails like this:

```
==> spirit_fingers
Compiling NIF crate :simhash (native/simhash)...
   Compiling unicode-xid v0.0.4
   Compiling void v1.0.2
   Compiling erlang_nif-sys v0.6.3
   Compiling quote v0.3.15
   Compiling unicode-segmentation v1.2.1
   Compiling siphasher v0.2.2
   Compiling lazy_static v0.1.16
   Compiling lazy_static v0.2.11
   Compiling unreachable v0.1.1
   Compiling synom v0.11.3
   Compiling simhash v0.2.0 (https://github.com/holsee/simhash-rs.git#7fc44d12)
   Compiling heck v0.3.0
error: failed to run custom build command for `erlang_nif-sys v0.6.3`
process didn't exit successfully: `/Users/leonid/Projects/ex_lsh/_build/dev/rustler_crates/simhash/release/build/erlang_nif-sys-bf350dda8055f7a2/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /Users/leonid/.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.3/build.rs:28:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

What does SpiritFinger require to build out-of-the-box?
* Erlang version?
* Elixir version?
* Rust version?

**Comment by holsee** [comment]
@soundmonster Hi, thanks for the report 👍.

I was targeting elixir ~> 1.6 (specifically 1.6.5) which uses OTP 20 and Rust 1.26.0.
_Had to check my Dockerfile in the project I was using this from for the specifics:_
* `FROM elixir:1.6.5`
* `RUN RUST_ARCHIVE="rust-1.26.0-x86_64-unknown-linux-gnu.tar.gz"`

I will look into this issue today, see if I can create a new release which works with elixir ~> 1.8, OTP 21, Rustler ~> 0.19, Rust 2018+

**Comment by holsee** [comment]
I created the 2 pull requests above in order to address this issue.  I will merge and push 2 new versions to hex.pm shortly.

0.1.3 ~ adds more detailed version notes.
0.2.0 ~ updates elixir and rust version support to latest stable.

**Comment by holsee** [comment]
@soundmonster I recommend you try with version `0.2.0` (via hex.pm) which using latest stable rust and elixir.

I will not be pushing the `0.1.3`* version to hex as it is a non-functional change, I just added docs and a git tag, but this likely won't concern you as you had issues with this specific version anyway.

**Comment by soundmonster** [comment]
Great, thank you! Will be trying it out today.
