### ISSUE TITLE
Fail to setup your lib

### ISSUE THREAD

**Issue by sveredyuk** [holsee/spirit_fingers#5]
Hey mates, thanks for the awesome contribution to the Elixir community. I tried to add this package to my phoenix app and a little bit confused about why it not working. Maybe I did something wrong. If you find some time to help I will be very appreciated.

```
elixir -> 1.11.1
rust -> 1.47.0

in mix.exs deps {:spirit_fingers, "~> 0.3.0"}
```

Looks like compilation passed weel:
```sh
mix deps.compile spirit_fingers:

Compiling NIF crate :simhash (native/simhash)...
    Finished release [optimized] target(s) in 0.02s
```

but when I started `iex -S mix` I can't access `SimHash` module and any of it functions. Feel so stupid to ask this but what I missed?

```elixir
SimHash.simhash("wow")
** (UndefinedFunctionError) function SimHash.simhash/1 is undefined (module SimHash is not available)
    SimHash.simhash("wow")
```

**Comment by holsee** [comment]
@sveredyuk no silly questions :)

I think you are missing the namespace.

```
iex(1)> SpiritFingers.SimHash.simhash("wow")
{:ok, 17399923637769257768}
```
